#!/bin/bash
# Cluster wrapper for one complete nested-LOCO XGBoost tuning run.
# Usage: bash scripts/jobs/run_xgb_nested_loco_tuning.sh <repro_data_root> [n_jobs] [n_trials] [country_variant] [run_id] [selection_objective] [fitting_mode] [optimizer] [parent_run_signature] [feature_scope] [include_manual_incumbent]
set -euo pipefail

if [ "$#" -lt 1 ] || [ "$#" -gt 11 ]; then
    echo "Usage: $0 <repro_data_root> [n_jobs] [n_trials] [country_variant] [run_id] [selection_objective] [fitting_mode] [optimizer] [parent_run_signature] [feature_scope] [include_manual_incumbent]" >&2
    exit 1
fi

REPRO_DATA_ROOT_ARG="$1"
N_JOBS="${2:-42}"
N_TRIALS="${3:-200}"
COUNTRY_VARIANT="${4:-a}"
RUN_ID="${5:-}"
SELECTION_OBJECTIVE="${6:-country_r2_p25}"
FITTING_MODE="${7:-nested_per_outer_country}"
OPTIMIZER="${8:-custom_gp}"
PARENT_RUN_SIGNATURE="${9:-}"
FEATURE_SCOPE="${10:-full_exposome}"
INCLUDE_MANUAL_INCUMBENT="${11:-1}"
if [ "${PARENT_RUN_SIGNATURE}" = "-" ]; then
    # ``submit_xgb_nested_loco_tuning.sh`` uses this explicit sentinel because
    # the cluster's ``run`` wrapper otherwise elides an empty positional arg.
    PARENT_RUN_SIGNATURE=""
fi
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${PROJECT_ROOT:-${SCRIPT_DIR}/../..}"
CLUSTER_ENV="${SCRIPT_DIR}/../env.sh"
if [ -f "${CLUSTER_ENV}" ]; then
    # shellcheck source=/dev/null
    source "${CLUSTER_ENV}"
fi

PYTHON_BIN="${PYTHON_BIN:-python}"
if ! command -v "${PYTHON_BIN}" >/dev/null 2>&1; then
    echo "ERROR: Python executable not found: ${PYTHON_BIN}" >&2
    exit 1
fi

export REPRO_DATA_ROOT="${REPRO_DATA_ROOT_ARG}"
export XGB_TUNING_BAGS="structural,functional"
export XGB_TUNING_RUNGS="xgb_tree_d1,xgb_tree_d2,xgb_tree_d3"
export XGB_TUNING_N_JOBS="${N_JOBS}"
export XGB_TUNING_N_TRIALS="${N_TRIALS}"
export XGB_TUNING_VARIANT="${COUNTRY_VARIANT}"
export XGB_TUNING_SELECTION_OBJECTIVE="${SELECTION_OBJECTIVE}"
export XGB_TUNING_FITTING_MODE="${FITTING_MODE}"
export XGB_TUNING_OPTIMIZER="${OPTIMIZER}"
export XGB_TUNING_FEATURE_SCOPE="${FEATURE_SCOPE}"
export XGB_TUNING_INCLUDE_MANUAL_INCUMBENT="${INCLUDE_MANUAL_INCUMBENT}"
unset XGB_TUNING_PARENT_RUN_SIGNATURE
if [ -n "${PARENT_RUN_SIGNATURE}" ]; then
    export XGB_TUNING_PARENT_RUN_SIGNATURE="${PARENT_RUN_SIGNATURE}"
fi
# Do not inherit a caller-provided identifier: the submitter passes the only
# accepted run id explicitly, and an accidental reuse must fail rather than
# point a fresh job at an earlier delivery directory.
unset XGB_TUNING_RUN_ID
if [ -n "${RUN_ID}" ]; then
    export XGB_TUNING_RUN_ID="${RUN_ID}"
fi
export MPLBACKEND="Agg"
export PYTHONPATH="${PROJECT_ROOT}/src:${PYTHONPATH:-}"
# One numerical thread per joblib worker; the tuning stage itself also pins it.
export OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1
# Force the versioned local policy and a full production run.
unset XGB_TUNING_SMOKE XGB_TUNING_COUNTRY_CONFIG
unset V3_EXCLUDE_COUNTRIES V3_EXCLUDE_DIAGNOSIS

cd "${PROJECT_ROOT}"
echo "================================================================"
echo "Nested-LOCO XGBoost tuning job"
echo "  REPRO_DATA_ROOT = ${REPRO_DATA_ROOT}"
echo "  BAGS            = ${XGB_TUNING_BAGS}"
echo "  RUNGS           = ${XGB_TUNING_RUNGS}"
echo "  N_TRIALS        = ${XGB_TUNING_N_TRIALS}"
echo "  N_JOBS          = ${XGB_TUNING_N_JOBS}"
echo "  COUNTRY_VARIANT = ${XGB_TUNING_VARIANT}"
echo "  SELECTION_OBJECTIVE = ${XGB_TUNING_SELECTION_OBJECTIVE}"
echo "  FITTING_MODE    = ${XGB_TUNING_FITTING_MODE}"
echo "  OPTIMIZER       = ${XGB_TUNING_OPTIMIZER}"
echo "  FEATURE_SCOPE   = ${XGB_TUNING_FEATURE_SCOPE}"
echo "  MANUAL_INCUMBENT = ${XGB_TUNING_INCLUDE_MANUAL_INCUMBENT}"
echo "  PARENT_RUN      = ${XGB_TUNING_PARENT_RUN_SIGNATURE:-<none>}"
echo "  RUN_ID          = ${XGB_TUNING_RUN_ID:-<timestamp generated by stage>}"
echo "  delivery root   = ${PROJECT_ROOT}/outputs/xgb_nested_loco_tuning/<new-run-signature>/"
echo "================================================================"

exec "${PYTHON_BIN}" -m repo_expo_hoi_bag.cli \
    --repro-data-root "${REPRO_DATA_ROOT}" \
    run sensitivity xgb-nested-loco-tuning
